---
# vim:ft=ansible:
- name: Check if Google Cloud SDK is installed
  command: gcloud version
  register: gcloud_installed
  changed_when: false
  ignore_errors: yes

- fail:
    msg: "Please make sure Google Cloud SDK is installed before executing the role."
  when: gcloud_installed | failed

- name: Check if instances are created
  command: "gcloud compute instances list --filter='name:{{ basic_config.name }}' --format='value(status)'"
  register: instance_created
  changed_when: false
  ignore_errors: yes

- name: Create instance on google cloud platform
  command: gcloud compute instances create "{{ basic_config.name }}" --boot-disk-size="{{basic_config.boot_disk_size}}"
  changed_when: false
  when: instance_created.stdout == ""

- name: Start instance if it's on TERMINATED status
  command: gcloud compute instances start "{{ basic_config.name }}"
  changed_when: false
  when: instance_created.stdout == "TERMINATED"

- name: "Generate {{ inventory_output_dir }}"
  template:
    src: inventory.ini.j2
    dest: "{{ inventory_output_file }}"
